### ISSUE TITLE
need a Good README.md

### ISSUE THREAD

**Issue by Arman-ali-khan-786** [Arman-ali-khan-786/TexttoSpeech#1]

**Comment by Pdfulkar** [comment]
I am Working over it.

**Comment by Pdfulkar** [comment]
Could you tell me about the API you used in the projects with the links to it?

**Comment by Arman-ali-khan-786** [comment]
yes @Pdfulkar  like i have used one of the components of web speech API ,, 
you can refer to this link : https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API#Browser_compatibility.

**Comment by Arman-ali-khan-786** [comment]
good work

**Comment by Pdfulkar** [comment]
Thank you.
