### ISSUE TITLE
Unable to select voice option on Android Smartphone.

### ISSUE THREAD

**Issue by theabhayprajapati** [Arman-ali-khan-786/TexttoSpeech#11]
![Screenshot_20220929-234158_Chrome.jpg](https://user-images.githubusercontent.com/88815641/193110623-c58609ef-4c46-4010-aaa2-1d7753ba43bc.jpg)

I tried click on the selection but nothing happened.

**Comment by ArunBohra12** [comment]
Yes, that seems to be an issue. Can I take this over to fix it?

**Comment by ArunBohra12** [comment]
Hi, I was able to solve this issue.
I will create a pull request regarding that.

**Comment by ArunBohra12** [comment]
I just want to ask if we can rename the master branch to main. Ref: [GitHub to replace "master" with alternative term to avoid slavery references](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references)

**Comment by Arman-ali-khan-786** [comment]
> Hi, I was able to solve this issue. I will create a pull request regarding that.

ok
