### ISSUE TITLE
Text Highlighting and Favicon

### ISSUE THREAD

**Issue by Janhvi52** [Arman-ali-khan-786/TexttoSpeech#12]
![Screenshot (43)](https://user-images.githubusercontent.com/97719669/193255570-7a541b19-3f0c-44cd-9c24-e7cb6fa58b09.png)

While reading the text, it doesn't show up which word it's pronouncing. Text highlighting that particular word while pronouncing the word can be done and a nice favicon can be added too!
Please assign me this issue for hacktoberfest2022 @Arman-ali-khan-786

**Comment by Arman-ali-khan-786** [comment]
> ![Screenshot (43)](https://user-images.githubusercontent.com/97719669/193255570-7a541b19-3f0c-44cd-9c24-e7cb6fa58b09.png)
> 
> While reading the text, it doesn't show up which word it's pronouncing. Text highlighting that particular word while pronouncing the word can be done and a nice favicon can be added too! Please assign me this issue for hacktoberfest2022 @Arman-ali-khan-786

nice , sure work on it looking forward to this issue

**Comment by Janhvi52** [comment]
> > ![Screenshot (43)](https://user-images.githubusercontent.com/97719669/193255570-7a541b19-3f0c-44cd-9c24-e7cb6fa58b09.png)
> > 
> > While reading the text, it doesn't show up which word it's pronouncing. Text highlighting that particular word while pronouncing the word can be done and a nice favicon can be added too! Please assign me this issue for hacktoberfest2022 @Arman-ali-khan-786
> 
> nice , sure work on it looking forward to this issue

Sure, Thankyou!

**Comment by Arman-ali-khan-786** [comment]
@Janhvi52 are you wroking on this issue??

**Comment by Janhvi52** [comment]
> @Janhvi52 are you wroking on this issue??

Yes ofcourse I'll be making the pull request within few days
rn I'm out of station pardon me from that

**Comment by Arman-ali-khan-786** [comment]
> > @Janhvi52 are you wroking on this issue??
> 
> Yes ofcourse I'll be making the pull request within few days rn I'm out of station pardon me from that

no issue

**Comment by Arman-ali-khan-786** [comment]
well done @Janhvi52
