### ISSUE TITLE
[FEATURE] Open graph image and description

### ISSUE THREAD

**Issue by Nakamcode** [Arman-ali-khan-786/TexttoSpeech#15]
### An open graph is a preview image that shows when a link is shared on social media
_for more info about open graphs read the blog below_
https://ahrefs.com/blog/open-graph-meta-tags/

**Comment by Arman-ali-khan-786** [comment]
> ### An open graph is a preview image that shows when a link is shared on social media
> _for more info about open graphs read the blog below_ https://ahrefs.com/blog/open-graph-meta-tags/

 would you like to work on it??

**Comment by Nakamcode** [comment]
Yes, I will like to work on this!

**Comment by Nakamcode** [comment]
thanks
