### ISSUE TITLE
need  a contributions.md file

### ISSUE THREAD

**Issue by Arman-ali-khan-786** [Arman-ali-khan-786/TexttoSpeech#2]
a well documented file on how to contribute to this project and step by step procedure to do .

**Comment by Pdfulkar** [comment]
Currently, I have a file I will make some changes to it.
let me know if that file will be acceptable or not.

**Comment by Arman-ali-khan-786** [comment]
> Currently, I have a file I will make some changes to it. let me know if that file will be acceptable or not.

let's see then make a pr and i will verify that

**Comment by Arman-ali-khan-786** [comment]
Great work @Pdfulkar

**Comment by Pdfulkar** [comment]
Thank you this is the first issue I solved.
I would love to work on such issues, @Arman-ali-khan-786  ping me if there are any.
