### ISSUE TITLE
make the ui responsive

### ISSUE THREAD

**Issue by Arman-ali-khan-786** [Arman-ali-khan-786/TexttoSpeech#4]

**Comment by Pdfulkar** [comment]
On it.

**Comment by Pdfulkar** [comment]
After creating UI good I will make it responsive in some way.

**Comment by Arman-ali-khan-786** [comment]
ok don't change any functionalities ..

**Comment by Arman-ali-khan-786** [comment]
@Pdfulkar hi bro are you still working to reslove this issue?

**Comment by navaneethmanoj** [comment]
Hi, can you assign me this issue if it hasn't been completed yet?

**Comment by Arman-ali-khan-786** [comment]
> Hi, can you assign me this issue if it hasn't been completed yet?

yeah

**Comment by vansh-attri** [comment]
Hi, If anyone is not working on this issue, Can you please assign it to me?

**Comment by vansh-attri** [comment]
@Arman-ali-khan-786, I think this is already responsive.

**Comment by Arman-ali-khan-786** [comment]
> @Arman-ali-khan-786, I think this is already responsive.
for most of the dimensions it is, but check for surface duo or galaxy flod and dimensions above 1280.. do check the rendering in different bowsers also...

**Comment by vansh-attri** [comment]
It is working completely fine -
<img width="208" alt="Screenshot 2023-10-05 135432" src="https://github.com/Arman-ali-khan-786/TexttoSpeech/assets/138808830/014f9a4b-e741-430e-a2f3-cfa069f09fd2">
<img width="156" alt="Screenshot 2023-10-05 135442" src="https://github.com/Arman-ali-khan-786/TexttoSpeech/assets/138808830/7724727a-9d7a-4879-8281-9ab0718efcc7">

**Comment by Arman-ali-khan-786** [comment]
@vansh-attri  see the button alignment pause btn going down, it should be on a single line as other btns or 2/2 evenly spaced okk

**Comment by vansh-attri** [comment]
Can I make display of these buttons grid?

**Comment by vansh-attri** [comment]
Made pull requset #22. Please check.
<img width="263" alt="Screenshot 2023-10-05 142617" src="https://github.com/Arman-ali-khan-786/TexttoSpeech/assets/138808830/8b201cc2-a428-4958-97ea-d3122bc9c64c">
<img width="104" alt="Screenshot 2023-10-05 142604" src="https://github.com/Arman-ali-khan-786/TexttoSpeech/assets/138808830/464f173c-005d-4b8f-aa43-c9b1629c6720">

**Comment by Arman-ali-khan-786** [comment]
good job @vansh-attri
