### ISSUE TITLE
re: ui improvement; replace text to icons in controls and add cursor pointer

### ISSUE THREAD

**Issue by chaaals** [Arman-ali-khan-786/TexttoSpeech#9]
Hi, can you please assign this issue to me @Arman-ali-khan-786 ?

Planning on replacing these texts in control buttons to icons
![image](https://user-images.githubusercontent.com/70326902/193101114-bf5ce2f2-bca0-4da2-8b58-22c18407966f.png)

**Comment by theabhayprajapati** [comment]
I can Solve it

**Comment by chaaals** [comment]
> I can Solve it

Hi! I already made a PR for this one

**Comment by theabhayprajapati** [comment]
yes I saw it later it's good

**Comment by theabhayprajapati** [comment]
> > I can Solve it
> 
> Hi! I already made a PR for this one

New UI is awesome 😎

**Comment by Arman-ali-khan-786** [comment]
> > I can Solve it
> 
> Hi! I already made a PR for this one

wait for hacktober fest to start then i will review it okk..

**Comment by chaaals** [comment]
> > > I can Solve it
> > 
> > 
> > Hi! I already made a PR for this one
> 
> wait for hacktober fest to start then i will review it okk..

gotcha! thankss
